// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectRTU(arg1:string,arg2:number,arg3:number,arg4:number,arg5:string):Promise<string>;

export function ConnectTCP(arg1:string):Promise<string>;

export function Disconnect():Promise<string>;

export function MaskWriteRegister(arg1:number,arg2:number,arg3:number):Promise<Array<number>>;

export function ReadCoils(arg1:number,arg2:number):Promise<Array<number>>;

export function ReadDiscreteInputs(arg1:number,arg2:number):Promise<Array<number>>;

export function ReadFIFOQueue(arg1:number):Promise<Array<number>>;

export function ReadHoldingRegisters(arg1:number,arg2:number):Promise<Array<number>>;

export function ReadInputRegisters(arg1:number,arg2:number):Promise<Array<number>>;

export function ReadWriteMultipleRegisters(arg1:number,arg2:number,arg3:number,arg4:number,arg5:Array<number>):Promise<Array<number>>;

export function WriteMultipleCoils(arg1:number,arg2:number,arg3:Array<number>):Promise<Array<number>>;

export function WriteMultipleRegisters(arg1:number,arg2:number,arg3:Array<number>):Promise<Array<number>>;

export function WriteSingleCoil(arg1:number,arg2:number):Promise<Array<number>>;

export function WriteSingleRegister(arg1:number,arg2:number):Promise<Array<number>>;
