// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectRTU(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['ModbusController']['ConnectRTU'](arg1, arg2, arg3, arg4, arg5);
}

export function ConnectTCP(arg1) {
  return window['go']['main']['ModbusController']['ConnectTCP'](arg1);
}

export function Disconnect() {
  return window['go']['main']['ModbusController']['Disconnect']();
}

export function MaskWriteRegister(arg1, arg2, arg3) {
  return window['go']['main']['ModbusController']['MaskWriteRegister'](arg1, arg2, arg3);
}

export function ReadCoils(arg1, arg2) {
  return window['go']['main']['ModbusController']['ReadCoils'](arg1, arg2);
}

export function ReadDiscreteInputs(arg1, arg2) {
  return window['go']['main']['ModbusController']['ReadDiscreteInputs'](arg1, arg2);
}

export function ReadFIFOQueue(arg1) {
  return window['go']['main']['ModbusController']['ReadFIFOQueue'](arg1);
}

export function ReadHoldingRegisters(arg1, arg2) {
  return window['go']['main']['ModbusController']['ReadHoldingRegisters'](arg1, arg2);
}

export function ReadInputRegisters(arg1, arg2) {
  return window['go']['main']['ModbusController']['ReadInputRegisters'](arg1, arg2);
}

export function ReadWriteMultipleRegisters(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['ModbusController']['ReadWriteMultipleRegisters'](arg1, arg2, arg3, arg4, arg5);
}

export function WriteMultipleCoils(arg1, arg2, arg3) {
  return window['go']['main']['ModbusController']['WriteMultipleCoils'](arg1, arg2, arg3);
}

export function WriteMultipleRegisters(arg1, arg2, arg3) {
  return window['go']['main']['ModbusController']['WriteMultipleRegisters'](arg1, arg2, arg3);
}

export function WriteSingleCoil(arg1, arg2) {
  return window['go']['main']['ModbusController']['WriteSingleCoil'](arg1, arg2);
}

export function WriteSingleRegister(arg1, arg2) {
  return window['go']['main']['ModbusController']['WriteSingleRegister'](arg1, arg2);
}
